Repository kaltura/playkit-js-dash, pull requests merged in 2018-11, with the labels that each got.

#64 feat(FEC-8553): add ability to force redirect kaltura playManifest urls
  karma.conf.js
  src/dash-adapter.js
  src/default-config.json
Labels: Type: Feature

#65 fix(FEC-8666): cannot play dash drm
  src/dash-adapter.js
Labels: Priority: High, Type: Bug

#67 fix(FEC-8711): live in IE has a small jump in the stream after a second
  src/dash-adapter.js
  test/src/dash-adapter.spec.js
Labels: Type: Bug

#68 chore: fix typo in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Priority: Low
