Repository kaltura/playkit-js-dash, pull requests merged in 2019-08, with the labels that each got.

#82 feat(FEC-9137): DRM protocol detection
  src/dash-adapter.js
  src/drm/playready.js
  src/drm/widevine.js
  test/src/dash-adapter.spec.js
  test/src/drm/playready.spec.js
  test/src/drm/widevine.spec.js
Labels: Type: Feature

#81 feat(FEC-9271): expose interface and methods to enable customising DRM request/response
  package.json
  src/dash-adapter.js
  yarn.lock
Labels: Priority: High, Type: Feature

#83 fix: logs for drm checks
  src/drm/widevine.js
Labels: Type: Bug
